language: node_js
node_js: stable
cache:
  apt: true
  directories:
  - node_modules
before_install:
  - openssl aes-256-cbc -K $encrypted_7a3a661e7d10_key -iv $encrypted_7a3a661e7d10_iv
    -in id_rsa_yangyong.enc -out ~/.ssh/id_rsa_yangyong -d
  - chmod 600 ~/.ssh/id_rsa_yangyong
  - echo -e "Host 121.36.50.216\n\tStrictHostKeyChecking no\n\tIdentityFile ~/.ssh/id_rsa_yangyong" >> ~/.ssh/config
addons:
  ssh_known_hosts: 121.36.50.216
install:
- npm install
script:
- npm run build
after_success:
- echo 准备移动至指定文件夹...
- travis_wait 30 scp -o stricthostkeychecking=no -rC ./build/* root@121.36.50.216:/root/hello-angus
